### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by kousu** [kousu/cache#1]
TravisCI is limited in what folders it will cache, but it is smart about detecting when they have been updated: https://docs.travis-ci.com/user/caching/.

In contrast, GithubCI's caching mechanism expects that you can pre-compute, from only the contents of your repo, a cache key to identify your cache. Caches are write-once in Github. The closest thing to updating a cache is by using `restore-keys` eg.

```
    - name: Download annex cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.annex-cache
        key: annex-${{ hashFiles('**/*.nii.gz, **/*.nii') }}
        restore-keys: |
          annex-
```

In this, `annex-` is a prefix of every cache, so if the exact cache doesn't exist yet, the most recently generated cache will be downloaded instead.

This is inconvenient, and can even fail if:

- you haven't precisely pinned your dependencies and they update under you
- some other content in your cache shifts

I don't want to have to think about all that.

The idea of this fork is to behave more like Travis: download the most recent cache, but then *upload*. So far, it needs to be used like this:

```
    - name: caching
      uses: kousu/cache@main
      with:
        path: .cache
        key: mycache-${{ hashFiles('.cache') }}
        restore-keys: |
          mycache-
```

because I haven't found where or if `hashFiles()` is available in the Github javascript libraries, it needs to be fed in from the Workflow language. You need to make sure the path used in `hashFiles()` matches the path used in `path:` and that the `restore-keys:` prefix matches the prefix used in `key:`. Another caveat is that hashFiles is strictly limited, I guess as an anti-abuse measure, to reading files **within your repo**, so you'll need to, I dunno, rsync or symlink or something to cache things in e.g. ~/.npm or ~/.cache/pip.
